// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGx4Dry1d0eLJ3ZuXKAxB2GlzF-O2HZ2o',
    appId: '1:1084599954975:web:3b8d2ddc7121b8df61af2a',
    messagingSenderId: '1084599954975',
    projectId: 'sampleapp-e1686',
    authDomain: 'sampleapp-e1686.firebaseapp.com',
    storageBucket: 'sampleapp-e1686.firebasestorage.app',
    measurementId: 'G-0T52VT2VXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ZjCp2hM66i2GC5uIlmziHnRuNi8CPes',
    appId: '1:1084599954975:android:f270f31f9e84831f61af2a',
    messagingSenderId: '1084599954975',
    projectId: 'sampleapp-e1686',
    storageBucket: 'sampleapp-e1686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM1M6Zi1ZEjKnohBEeLgQLzjdEwk1Fsl0',
    appId: '1:1084599954975:ios:dfafd32f2f31114961af2a',
    messagingSenderId: '1084599954975',
    projectId: 'sampleapp-e1686',
    storageBucket: 'sampleapp-e1686.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM1M6Zi1ZEjKnohBEeLgQLzjdEwk1Fsl0',
    appId: '1:1084599954975:ios:dfafd32f2f31114961af2a',
    messagingSenderId: '1084599954975',
    projectId: 'sampleapp-e1686',
    storageBucket: 'sampleapp-e1686.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGx4Dry1d0eLJ3ZuXKAxB2GlzF-O2HZ2o',
    appId: '1:1084599954975:web:621f30b4fc66583861af2a',
    messagingSenderId: '1084599954975',
    projectId: 'sampleapp-e1686',
    authDomain: 'sampleapp-e1686.firebaseapp.com',
    storageBucket: 'sampleapp-e1686.firebasestorage.app',
    measurementId: 'G-MNXZGQ3Z82',
  );
}
